# Import Fall 2024 enrollment data for student body demographics calculation

In [19]:
!{sys.executable} -m pip install pandasgui

  Using cached pandasgui-0.2.15.tar.gz (217 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Using cached pynput-1.8.1-py2.py3-none-any.whl.metadata (32 kB)
  Using cached astor-0.8.1-py2.py3-none-any.whl.metadata (4.2 kB)
  Using cached qtstylish-0.1.5.tar.gz (983 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Using cached astor-0.8.1-py2.py3-none-any.whl (27 kB)
Using cached pynput-1.8.1-py2.py3-none-any.whl (91 kB)
  Created wheel for pandasgui: filename=pandasgui-0.2.15-py3-none-any.whl size=235443 sha256=490bca16cbbeb8af6274bc0786ac2c82f8d0aad5b7295c5094445b1360829763
  Stored in directory: c:\users\iabak\appdata\local\pip\cache\wheels\20\3d\f8\821f3ab82c2c6b5a717b760e2ea07f90ad4321dc0f7ffedcb1
  Created wheel for qtstylish: filename=qtstylish-0.1.5-py3-none-any.whl size=1029282 sha256=501a006e520ea931e1e9aa7ac3479fa9153bc7066c49e0b52257806b54763398
  Stored in dir

In [31]:
import bokeh
import os

print("Bokeh is being loaded from:")
print(bokeh.__file__)
print("Version:", getattr(bokeh, '__version__', 'No __version__ attribute'))

Bokeh is being loaded from:
C:\Users\iabak\anaconda3\Lib\site-packages\bokeh\__init__.py
Version: 3.6.0


In [33]:
pip install bokeh==3.3.4

   ---------------------------------------- 0.0/6.8 MB ? eta -:--:--
   ---- ----------------------------------- 0.8/6.8 MB 4.8 MB/s eta 0:00:02
   --------- ------------------------------ 1.6/6.8 MB 4.4 MB/s eta 0:00:02
   ------------ --------------------------- 2.1/6.8 MB 3.6 MB/s eta 0:00:02
   ------------- -------------------------- 2.4/6.8 MB 3.1 MB/s eta 0:00:02
   --------------- ------------------------ 2.6/6.8 MB 2.9 MB/s eta 0:00:02
   ------------------ --------------------- 3.1/6.8 MB 2.6 MB/s eta 0:00:02
   ------------------- -------------------- 3.4/6.8 MB 2.5 MB/s eta 0:00:02
   --------------------- ------------------ 3.7/6.8 MB 2.4 MB/s eta 0:00:02
   ----------------------- ---------------- 3.9/6.8 MB 2.3 MB/s eta 0:00:02
   ------------------------ --------------- 4.2/6.8 MB 2.1 MB/s eta 0:00:02
   -------------------------- ------------- 4.5/6.8 MB 2.0 MB/s eta 0:00:02
   --------------------------- ------------ 4.7/6.8 MB 2.0 MB/s eta 0:00:02
   ----------------

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
panel 1.5.2 requires bokeh<3.7.0,>=3.5.0, but you have bokeh 3.3.4 which is incompatible.


In [1]:
import pandas as pd
import numpy as np
import statsmodels.api as sm
from pandasgui import show
file_path = r"P:\IE Office_Current\External Reporting - IPEDS\2024-2025\4 Spring Collection\Fall Enrollment\2024-25 Fall enrollment dataset BASE FILE.xlsx"
FallEnrollment = pd.read_excel(file_path)
FallEnrollment.rename(columns={'StudentId': 'ACPHSID'}, inplace=True)
FallEnrollment = FallEnrollment[~FallEnrollment['Major1'].str.contains("SPEC", na=False)] #the tilde negates the SPEC, meaning drop SPECs
gui = show(FallEnrollment)

PandasGUI INFO — pandasgui.gui — Opening PandasGUI
C:\Users\iabak\AppData\Local\Temp\ipykernel_5368\3193896121.py:9: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  gui = show(FallEnrollment)
C:\Users\iabak\AppData\Local\Temp\ipykernel_5368\3193896121.py:9: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  gui = show(FallEnrollment)
C:\Users\iabak\AppData\Local\Temp\ipykernel_5368\3193896121.py:9: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[po

In [3]:
print(FallEnrollment.columns)

Index(['Major1', 'CIPCode', 'acadlevel', 'UGStatus', 'degreetype',
       'TypeOfStudent', 'InitialCohort', 'CollegeLevel', 'ConcatMajor',
       'Major2', 'CurrentTerm', 'ACPHSID', 'FirstName', 'LastName',
       'PreferredName', 'FullName', 'Email', 'BirthDate', 'Age', 'Major3',
       'ClassLevel', 'Lvl1MajorSplit1', 'Lvl1MajorSplit2', 'Lvl1MajorSplit3',
       'Lvl1MajorSplit4', 'Lvl2Major', 'ClassGroupCohort', 'Currentflag1',
       'Lvl1DegreeEarned', 'D1AcademicStatus1', 'Lvl1CumCreditsEarned',
       'Lvl1CumulativeGPA', 'Currentflag2', 'D2AcademicStatus1',
       'Lvl2CumCreditsEarned', 'Lvl2CumulativeGPA', 'SemCreditsTaken',
       'CumCrdtTowardCum', 'Lvl1Major', 'Affiliation', 'MobilePhone',
       'BillingAddressOne', 'BillingAddressTwo', 'BillingCity', 'BillingState',
       'BillingProvince', 'BillingZip', 'BillingCountry', 'Lvl1StartDate',
       'Lvl1EndDate', 'InitialTermName', 'ExpGradTerm1', 'ExpGradTerm2',
       'Lvl2StartDate', 'Lvl2EndDate', 'CurrentflagSp', 'De

In [5]:
num_rows=FallEnrollment.shape[0]
print(num_rows)

856


In [7]:
sex_counts=FallEnrollment['Sex'].value_counts(dropna=False)
print(sex_counts)

Sex
F    531
M    305
U     19
T      1
Name: count, dtype: int64


In [9]:
ethnic_counts=FallEnrollment['Ethniccode'].value_counts(dropna=False)
print(ethnic_counts)

Ethniccode
WHITE              395
ASIAN              175
BLACK, AFR AMER     90
HISPANIC ANY        60
UNKNOWN             50
NON RES ALIEN       41
TWO + RACES         40
AMER. IND/ALASK      5
Name: count, dtype: int64


# Import Spring 2025 list of students on probation and inspect

In [17]:
file_path_2 = r"P:\IE Office_Current\Data Requests\2025\Probation demographics for Jonathan Phipps\ASCFall2024.xlsx"
Spring25Prob = pd.read_excel(file_path_2)
Spring25Prob.rename(columns={'Id Number': 'ACPHSID'}, inplace=True)
Spring25Prob=Spring25Prob[Spring25Prob['Decision'].str.contains('Probation', case=False, na=False)]
FallEnrollment = FallEnrollment[~FallEnrollment['Major1'].str.contains("SPEC", na=False)] #the tilde negates the SPEC, meaning drop SPECs
gui = show(Spring25Prob)

PandasGUI INFO — pandasgui.gui — Opening PandasGUI
C:\Users\iabak\AppData\Local\Temp\ipykernel_5368\3234731589.py:6: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

C:\Users\iabak\AppData\Local\Temp\ipykernel_5368\3234731589.py:6: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

C:\Users\iabak\AppData\Local\Temp\ipykernel_5368\3234731589.py:6: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

C:\Users\iabak\AppData\Local\Temp\ipykernel_5368\

In [19]:
num_rows=Spring25Prob.shape[0]
print(num_rows)

83


# Merge Fall 2024 data and Spring 25 probation data

In [21]:
merged_df=pd.merge(FallEnrollment, Spring25Prob, on='ACPHSID', how='left', indicator=True)
merged_df = merged_df[['_merge', 'CollegeLevel', 'Ethniccode', 'Sex', 'Major1', 'Decision']]
merged_df.rename(columns={'Ethniccode': 'Ethnicity'}, inplace=True)
merged_df.rename(columns={'Major1': 'Major 1'}, inplace=True)
merged_df.rename(columns={'Sex': 'Gender'}, inplace=True)
merged_df.rename(columns={'CollegeLevel': 'College Level'}, inplace=True)
merged_df['DecisionRecode'] = merged_df['Decision'].str.contains('Probation', case=False, na=False).astype(int)
merged_df['URM'] = merged_df['Ethnicity'].str.contains('WHITE', case=False, na=False).apply(lambda x: 0 if x else 1)
merged_df['IntlStudent'] = np.where(
    merged_df['Ethnicity'].str.contains('NON RES', case=False, na=False),
    1,
    0
)
gui = show(merged_df)

PandasGUI INFO — pandasgui.gui — Opening PandasGUI
C:\Users\iabak\AppData\Local\Temp\ipykernel_5368\2906790849.py:14: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

C:\Users\iabak\AppData\Local\Temp\ipykernel_5368\2906790849.py:14: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

C:\Users\iabak\AppData\Local\Temp\ipykernel_5368\2906790849.py:14: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

C:\Users\iabak\AppData\Local\Temp\ipykernel_53

In [23]:
print(merged_df.head())

      _merge College Level    Ethnicity Gender  \
0  left_only  3 Third Year  TWO + RACES      M   
1  left_only  1 First Year        ASIAN      F   
2  left_only  1 First Year        WHITE      M   
3  left_only  1 First Year        ASIAN      M   
4  left_only  1 First Year        ASIAN      F   

                                             Major 1 Decision  DecisionRecode  \
0  BS Biology                                    ...      NaN               0   
1                                         BS Biology      NaN               0   
2                                         BS Biology      NaN               0   
3                                         BS Biology      NaN               0   
4                                         BS Biology      NaN               0   

   URM  IntlStudent  
0    1            0  
1    1            0  
2    0            0  
3    1            0  
4    1            0  


In [25]:
ethnic_counts=merged_df['Ethnicity'].value_counts(dropna=False)
print(ethnic_counts)

Ethnicity
WHITE              395
ASIAN              175
BLACK, AFR AMER     90
HISPANIC ANY        60
UNKNOWN             50
NON RES ALIEN       41
TWO + RACES         40
AMER. IND/ALASK      5
Name: count, dtype: int64


In [27]:
urm_counts=merged_df['URM'].value_counts(dropna=False)
print(urm_counts)

URM
1    461
0    395
Name: count, dtype: int64


In [29]:
merged_df['IntlStudent'] = np.where(merged_df['Ethnicity'] == 'NON RES ALIEN', 1, 0)
gui = show(merged_df)

PandasGUI INFO — pandasgui.gui — Opening PandasGUI
C:\Users\iabak\AppData\Local\Temp\ipykernel_5368\2366857434.py:2: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

C:\Users\iabak\AppData\Local\Temp\ipykernel_5368\2366857434.py:2: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

C:\Users\iabak\AppData\Local\Temp\ipykernel_5368\2366857434.py:2: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

C:\Users\iabak\AppData\Local\Temp\ipykernel_5368\

In [31]:
probation_counts=merged_df['DecisionRecode'].value_counts(dropna=False)
print(probation_counts)

DecisionRecode
0    773
1     83
Name: count, dtype: int64


# Chi Square for sex (M vs F)

In [33]:
filtered_df = merged_df[(merged_df['DecisionRecode'] == 1) & (merged_df['Gender'].isin(['F', 'M']))]
sex_tabulation=filtered_df['Gender'].value_counts()
print(sex_tabulation)

Gender
F    50
M    27
Name: count, dtype: int64


In [35]:
filtered_df = merged_df[(merged_df['DecisionRecode'] == 1)]
ethnic_tab=filtered_df['Ethnicity'].value_counts()
print(ethnic_tab)

Ethnicity
WHITE              37
BLACK, AFR AMER    15
ASIAN               9
UNKNOWN             7
TWO + RACES         6
HISPANIC ANY        4
NON RES ALIEN       3
AMER. IND/ALASK     2
Name: count, dtype: int64


In [37]:
from scipy.stats import chi2_contingency
filtered_df = merged_df[merged_df['Gender'].isin(['F', 'M'])]
contingency_table = pd.crosstab(filtered_df['Gender'], filtered_df['DecisionRecode'])
chi2_stat, p_value, dof, expected = chi2_contingency(contingency_table)
N=filtered_df.shape[0]
print(f"Number of observations (N): {N}")
print(f"Chi-square statistic: {chi2_stat}")
print(f"P-value: {p_value}")
print(f"Degrees of freedom: {dof}")
print(f"Expected frequencies table:\n{expected}")

Number of observations (N): 836
Chi-square statistic: 0.021641622327803457
P-value: 0.8830444719664452
Degrees of freedom: 1
Expected frequencies table:
[[482.09210526  48.90789474]
 [276.90789474  28.09210526]]


In [39]:
from scipy.stats import fisher_exact
# Filter the data
filtered_df = merged_df[merged_df['Gender'].isin(['F', 'M'])]
# Create contingency table
contingency_table = pd.crosstab(filtered_df['Gender'], filtered_df['DecisionRecode'])
# Perform Fisher's Exact Test
odds_ratio, p_value = fisher_exact(contingency_table)
# Get the number of observations
N = filtered_df.shape[0]  # Number of rows in the filtered dataframe
# Print results
print(f"Number of observations (N): {N}")
print(f"Odds ratio: {odds_ratio}")
print(f"P-value: {p_value}")

Number of observations (N): 836
Odds ratio: 0.9343165467625899
P-value: 0.9012037309533517


# Chi Square for ethnicity, then regression for ethnicity

In [41]:
filtered_df = merged_df[merged_df['Ethnicity'] != 'UNKNOWN']
contingency_table = pd.crosstab(filtered_df['URM'], filtered_df['DecisionRecode'])
chi2_stat, p_value, dof, expected = chi2_contingency(contingency_table)
N=filtered_df.shape[0]
print(f"Number of observations (N): {N}")
print(f"Chi-square statistic: {chi2_stat}")
print(f"P-value: {p_value}")
print(f"Degrees of freedom: {dof}")
print(f"Expected frequencies table:\n{expected}")

Number of observations (N): 806
Chi-square statistic: 0.0
P-value: 1.0
Degrees of freedom: 1
Expected frequencies table:
[[357.75434243  37.24565757]
 [372.24565757  38.75434243]]


In [43]:
from scipy.stats import fisher_exact
# Create contingency table
contingency_table = pd.crosstab(filtered_df['URM'], filtered_df['DecisionRecode'])
# Perform Fisher's Exact Test
odds_ratio, p_value = fisher_exact(contingency_table)
# Get the number of observations
N = filtered_df.shape[0]  # Number of rows in the filtered dataframe
# Print results
print(f"Number of observations (N): {N}")
print(f"Odds ratio: {odds_ratio}")
print(f"P-value: {p_value}")

Number of observations (N): 806
Odds ratio: 1.0143853530950304
P-value: 1.0


In [45]:
import statsmodels.api as sm
import statsmodels.formula.api as smf
filtered_df = merged_df[merged_df['Gender'].isin(['F', 'M'])]
# Assuming 'filtered_df' is your DataFrame, and 'DecisionRecode', 'URM', 'Sex' are columns

# Use the formula interface for the regression, specifying categorical variables with C()
formula = 'DecisionRecode ~ C(URM) + C(Gender)'

# Fit the regression model with robust standard errors (HC3)
model = smf.ols(formula, data=filtered_df)
results = model.fit(cov_type='HC3')

# Display the results
print(results.summary())

                            OLS Regression Results                            
Dep. Variable:         DecisionRecode   R-squared:                       0.000
Model:                            OLS   Adj. R-squared:                 -0.002
Method:                 Least Squares   F-statistic:                    0.1220
Date:                Thu, 05 Jun 2025   Prob (F-statistic):              0.885
Time:                        21:42:32   Log-Likelihood:                -148.85
No. Observations:                 836   AIC:                             303.7
Df Residuals:                     833   BIC:                             317.9
Df Model:                           2                                         
Covariance Type:                  HC3                                         
                     coef    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------
Intercept          0.0895      0.016      5.

# Chi square for international student status

In [47]:
filtered_df = merged_df
contingency_table=pd.crosstab(merged_df['IntlStudent'], merged_df['DecisionRecode'])
chi2_stat, p_value, dof, expecgted=chi2_contingency(contingency_table)
N=filtered_df.shape[0]
print(f"Number of observations (N): {N}")
print(f"Chi-square statistic: {chi2_stat}")
print(f"P-value: {p_value}")
print(f"Degrees of freedom: {dof}")
print(f"Expected frequencies table:\n{expected}")

Number of observations (N): 856
Chi-square statistic: 0.0661398996079052
P-value: 0.7970423030132371
Degrees of freedom: 1
Expected frequencies table:
[[357.75434243  37.24565757]
 [372.24565757  38.75434243]]


In [49]:
filtered_df = merged_df
# Create contingency table
contingency_table = pd.crosstab(filtered_df['IntlStudent'], filtered_df['DecisionRecode'])
# Perform Fisher's Exact Test
odds_ratio, p_value = fisher_exact(contingency_table)
# Get the number of observations
N = filtered_df.shape[0]  # Number of rows in the filtered dataframe
# Print results
print(f"Number of observations (N): {N}")
print(f"Odds ratio: {odds_ratio}")
print(f"P-value: {p_value}")

Number of observations (N): 856
Odds ratio: 0.725328947368421
P-value: 0.7892807415833922


# Import Spring 2025 frozen file for demographic tabulations

In [53]:
import pandas as pd
import numpy as np
import statsmodels.api as sm
file_path2 = r"P:\IE Office_Current\CAMS Frozen Files\2024-2025\Spring 2025\Spring 2025 frozen file_FINAL.xlsx"
SpringEnrollment = pd.read_excel(file_path2)
SpringEnrollment.rename(columns={'Student ID': 'ACPHSID'}, inplace=True)
SpringEnrollment = SpringEnrollment[~SpringEnrollment['Major 1'].str.contains("SPEC", na=False)] #the tilde negates the SPEC, meaning drop SPECs
gui = show(SpringEnrollment)

PandasGUI INFO — pandasgui.gui — Opening PandasGUI
C:\Users\iabak\AppData\Local\Temp\ipykernel_5368\3839035755.py:8: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

C:\Users\iabak\AppData\Local\Temp\ipykernel_5368\3839035755.py:8: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

C:\Users\iabak\AppData\Local\Temp\ipykernel_5368\3839035755.py:8: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

C:\Users\iabak\AppData\Local\Temp\ipykernel_5368\

In [55]:
print(SpringEnrollment.columns)

Index(['Term', 'ACPHSID', 'First Name', 'Last Name', 'Preferred Name',
       'Full Name', 'Birth Date', 'Age as of Term Census Date',
       'College Level', 'Enrollment Type', 'Initial Cohort', 'ACPHS Email',
       'Mobile Phone', 'Permanent Address Line 1', 'Permanent Address Line 2',
       'Permanent Address City', 'Permanent Address State/province',
       'Permanent Address Zip', 'Permanent Address Country',
       'Current Address Line 1', 'Current Address Line 2',
       'Current Address City', 'Current Address State/province',
       'Current Address Zip', 'Current Address Country',
       'Billing Address Line 1', 'Billing Address Line 2',
       'Billing Address City', 'Billing Address State/province',
       'Billing Address Zip', 'Billing Address Country', 'Primary Major',
       'Program Affiliation', 'Currentflag1', 'Major 1',
       'Major1 Academic Status', 'Major1 Earned', 'Major1 Degree Name',
       'Major1 Degree Major', 'Major1 Start Date', 'Major1 Expected Date

In [57]:
num_rows=SpringEnrollment.shape[0]
print(num_rows)

812


In [59]:
sex_counts=SpringEnrollment['Gender'].value_counts(dropna=False)
print(sex_counts)

Gender
F    501
M    292
U     19
Name: count, dtype: int64


In [61]:
ethnic_counts=SpringEnrollment['Ethnicity'].value_counts(dropna=False)
print(ethnic_counts)

Ethnicity
White                                                                                                                       332
Asian                                                                                                                       153
Race/Ethnicity Unknown                                                                                                      104
Black or African American                                                                                                    69
Hispanics of any race                                                                                                        68
Two or more races                                                                                                            49
Nonresident Alien                                                                                                            35
American Indian or Alaska Native                                                              

# Import Spring 2025 probation list and inspect

In [65]:
file_path_3 = r"P:\IE Office_Current\Data Requests\2025\Probation demographics for Jonathan Phipps\Spring2025ASCReport.xlsx"
Fall25Prob = pd.read_excel(file_path_3)
Fall25Prob.rename(columns={'Id Number': 'ACPHSID'}, inplace=True)
Fall25Prob=Fall25Prob[Fall25Prob['Decision'].str.contains('Probation', case=False, na=False)]
Fall25Prob = Fall25Prob[['ACPHSID', 'Decision']]
gui = show(Fall25Prob)

PandasGUI INFO — pandasgui.gui — Opening PandasGUI
C:\Users\iabak\AppData\Local\Temp\ipykernel_5368\4033130178.py:6: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

C:\Users\iabak\AppData\Local\Temp\ipykernel_5368\4033130178.py:6: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

C:\Users\iabak\AppData\Local\Temp\ipykernel_5368\4033130178.py:6: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

C:\Users\iabak\AppData\Local\Temp\ipykernel_5368\

In [71]:
Fall25Prob.shape[0]
gui=show(Fall25Prob)


PandasGUI INFO — pandasgui.gui — Opening PandasGUI
C:\Users\iabak\AppData\Local\Temp\ipykernel_5368\773974558.py:2: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

C:\Users\iabak\AppData\Local\Temp\ipykernel_5368\773974558.py:2: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

C:\Users\iabak\AppData\Local\Temp\ipykernel_5368\773974558.py:2: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

C:\Users\iabak\AppData\Local\Temp\ipykernel_5368\773

# Merge Spring 2025 frozen file and SP25 probation decisions

In [73]:
merged_df2=pd.merge(SpringEnrollment, Fall25Prob, on='ACPHSID', how='left', indicator=True)
print(merged_df2.columns)

Index(['Term', 'ACPHSID', 'First Name', 'Last Name', 'Preferred Name',
       'Full Name', 'Birth Date', 'Age as of Term Census Date',
       'College Level', 'Enrollment Type',
       ...
       'College Transferring From', 'Number College Credits Transferred',
       'Is Commuter', 'Is Transfer', 'Is First Generation',
       'Is Student Athlete', 'Professional Gpa', 'UG vs Grad', 'Decision',
       '_merge'],
      dtype='object', length=102)


In [75]:
merged_df2 = merged_df2[['_merge', 'First Name', 'Last Name', 'Ethnicity', 'College Level', 'Gender', 'Decision']].copy()
merged_df2['DecisionRecode'] = merged_df2['Decision'].str.contains('Probation', case=False, na=False).astype(int)
merged_df2['URM'] = merged_df2['Ethnicity'].str.contains('White', case=False, na=False).apply(lambda x: 0 if x else 1)
probation_counts=merged_df2['DecisionRecode'].value_counts(dropna=False)
print(probation_counts)

DecisionRecode
0    760
1     52
Name: count, dtype: int64


In [77]:
ethnic_counts=merged_df2['Ethnicity'].value_counts(dropna=False)
print(ethnic_counts)

Ethnicity
White                                                                                                                       332
Asian                                                                                                                       153
Race/Ethnicity Unknown                                                                                                      104
Black or African American                                                                                                    69
Hispanics of any race                                                                                                        68
Two or more races                                                                                                            49
Nonresident Alien                                                                                                            35
American Indian or Alaska Native                                                              

In [79]:
urm_counts=merged_df2['URM'].value_counts(dropna=False)
print(urm_counts)

URM
1    480
0    332
Name: count, dtype: int64


In [81]:
merged_df2['IntlStudent'] = np.where(
    merged_df2['Ethnicity'].str.contains('Nonresident', case=False, na=False),
    1,
    0
)
gui = show(merged_df2)

PandasGUI INFO — pandasgui.gui — Opening PandasGUI
C:\Users\iabak\AppData\Local\Temp\ipykernel_5368\2011557753.py:6: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

C:\Users\iabak\AppData\Local\Temp\ipykernel_5368\2011557753.py:6: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

C:\Users\iabak\AppData\Local\Temp\ipykernel_5368\2011557753.py:6: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

C:\Users\iabak\AppData\Local\Temp\ipykernel_5368\

In [83]:
probation_counts=merged_df2['DecisionRecode'].value_counts(dropna=False)
print(probation_counts)

DecisionRecode
0    760
1     52
Name: count, dtype: int64


# Chi Square for sex (M vs F)

In [85]:
filtered_df2 = merged_df2[(merged_df2['DecisionRecode'] == 1) & (merged_df2['Gender'].isin(['F', 'M', 'U']))]
sex_tabulation=filtered_df2['Gender'].value_counts()
print(sex_tabulation)

Gender
F    30
M    18
U     4
Name: count, dtype: int64


In [89]:
filtered_df2 = merged_df2[(merged_df2['DecisionRecode'] == 1)]
ethnic_tab=filtered_df2['Ethnicity'].value_counts()
print(ethnic_tab)
gui=show(ethnic_tab)

PandasGUI INFO — pandasgui.gui — Opening PandasGUI


Ethnicity
White                                                                                                                       20
Asian                                                                                                                        9
Race/Ethnicity Unknown                                                                                                       7
Two or more races                                                                                                            6
Hispanics of any race                                                                                                        4
Black or African American                                                                                                    4
Nonresident Alien                                                                                                            2
Name: count, dtype: int64


C:\Users\iabak\AppData\Local\Temp\ipykernel_5368\2445066883.py:4: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

C:\Users\iabak\AppData\Local\Temp\ipykernel_5368\2445066883.py:4: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

C:\Users\iabak\AppData\Local\Temp\ipykernel_5368\2445066883.py:4: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

C:\Users\iabak\AppData\Local\Temp\ipykernel_5368\2445066883.py:4: FutureWarning:

Series.__getitem__

In [91]:
from scipy.stats import chi2_contingency
filtered_df2 = merged_df2[merged_df2['Gender'].isin(['F', 'M'])]
contingency_table = pd.crosstab(filtered_df2['Gender'], filtered_df2['DecisionRecode'])
chi2_stat, p_value, dof, expected = chi2_contingency(contingency_table)
N=filtered_df2.shape[0]
print(f"Number of observations (N): {N}")
print(f"Chi-square statistic: {chi2_stat}")
print(f"P-value: {p_value}")
print(f"Degrees of freedom: {dof}")
print(f"Expected frequencies table:\n{expected}")

Number of observations (N): 793
Chi-square statistic: 0.0
P-value: 1.0
Degrees of freedom: 1
Expected frequencies table:
[[470.67465322  30.32534678]
 [274.32534678  17.67465322]]


In [93]:
from scipy.stats import fisher_exact
# Filter the data
filtered_df2 = merged_df2[merged_df2['Gender'].isin(['F', 'M'])]
# Create contingency table
contingency_table = pd.crosstab(filtered_df2['Gender'], filtered_df2['DecisionRecode'])
# Perform Fisher's Exact Test
odds_ratio, p_value = fisher_exact(contingency_table)
# Get the number of observations
N = filtered_df2.shape[0]  # Number of rows in the filtered dataframe
# Print results
print(f"Number of observations (N): {N}")
print(f"Odds ratio: {odds_ratio}")
print(f"P-value: {p_value}")

Number of observations (N): 793
Odds ratio: 1.0313868613138686
P-value: 1.0


# ChiSqauare for ethnicity, then regression

In [95]:
filtered_df2 = merged_df2[~merged_df2['Ethnicity'].str.contains('Unknown', case=False, na=False)]
contingency_table = pd.crosstab(filtered_df2['URM'], filtered_df2['DecisionRecode'])
chi2_stat, p_value, dof, expected = chi2_contingency(contingency_table)
N=filtered_df2.shape[0]
print(f"Number of observations (N): {N}")
print(f"Chi-square statistic: {chi2_stat}")
print(f"P-value: {p_value}")
print(f"Degrees of freedom: {dof}")
print(f"Expected frequencies table:\n{expected}")

Number of observations (N): 708
Chi-square statistic: 0.03449852166923235
P-value: 0.8526504022817167
Degrees of freedom: 1
Expected frequencies table:
[[310.89830508  21.10169492]
 [352.10169492  23.89830508]]


In [97]:
from scipy.stats import fisher_exact
# Create contingency table
contingency_table = pd.crosstab(filtered_df2['URM'], filtered_df2['DecisionRecode'])
# Perform Fisher's Exact Test
odds_ratio, p_value = fisher_exact(contingency_table)
# Get the number of observations
N = filtered_df2.shape[0]  # Number of rows in the filtered dataframe
# Print results
print(f"Number of observations (N): {N}")
print(f"Odds ratio: {odds_ratio}")
print(f"P-value: {p_value}")

Number of observations (N): 708
Odds ratio: 1.1111111111111112
P-value: 0.7598935897452263


In [99]:
import statsmodels.api as sm
import statsmodels.formula.api as smf
filtered_df2 = merged_df2[merged_df2['Gender'].isin(['F', 'M'])]
# Assuming 'filtered_df' is your DataFrame, and 'DecisionRecode', 'URM', 'Sex' are columns

# Use the formula interface for the regression, specifying categorical variables with C()
formula = 'DecisionRecode ~ C(URM) + C(Gender)'

# Fit the regression model with robust standard errors (HC3)
model = smf.ols(formula, data=filtered_df2)
results = model.fit(cov_type='HC3')

# Display the results
print(results.summary())

                            OLS Regression Results                            
Dep. Variable:         DecisionRecode   R-squared:                       0.001
Model:                            OLS   Adj. R-squared:                 -0.002
Method:                 Least Squares   F-statistic:                    0.3877
Date:                Thu, 05 Jun 2025   Prob (F-statistic):              0.679
Time:                        21:47:14   Log-Likelihood:                 11.953
No. Observations:                 793   AIC:                            -17.91
Df Residuals:                     790   BIC:                            -3.878
Df Model:                           2                                         
Covariance Type:                  HC3                                         
                     coef    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------
Intercept          0.0509      0.014      3.

# Chi Square for international students

In [101]:
filtered_df2 = merged_df2
contingency_table=pd.crosstab(merged_df2['IntlStudent'], merged_df2['DecisionRecode'])
chi2_stat, p_value, dof, expecgted=chi2_contingency(contingency_table)
N=filtered_df2.shape[0]
print(f"Number of observations (N): {N}")
print(f"Chi-square statistic: {chi2_stat}")
print(f"P-value: {p_value}")
print(f"Degrees of freedom: {dof}")
print(f"Expected frequencies table:\n{expected}")

Number of observations (N): 812
Chi-square statistic: 0.0
P-value: 1.0
Degrees of freedom: 1
Expected frequencies table:
[[310.89830508  21.10169492]
 [352.10169492  23.89830508]]


In [103]:
filtered_df2 = merged_df2
# Create contingency table
contingency_table = pd.crosstab(filtered_df2['IntlStudent'], filtered_df2['DecisionRecode'])
# Perform Fisher's Exact Test
odds_ratio, p_value = fisher_exact(contingency_table)
# Get the number of observations
N = filtered_df2.shape[0]  # Number of rows in the filtered dataframe
# Print results
print(f"Number of observations (N): {N}")
print(f"Odds ratio: {odds_ratio}")
print(f"P-value: {p_value}")

Number of observations (N): 812
Odds ratio: 0.8812121212121212
P-value: 1.0


# Append Spring 2025 merged df and Fall 2025 merged df

In [105]:
combinedDF = pd.concat([merged_df, merged_df2], ignore_index=True)
gui = show(combinedDF)

PandasGUI INFO — pandasgui.gui — Opening PandasGUI
C:\Users\iabak\AppData\Local\Temp\ipykernel_5368\4110255676.py:2: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

C:\Users\iabak\AppData\Local\Temp\ipykernel_5368\4110255676.py:2: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

C:\Users\iabak\AppData\Local\Temp\ipykernel_5368\4110255676.py:2: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

C:\Users\iabak\AppData\Local\Temp\ipykernel_5368\

In [107]:
ethnic_counts=combinedDF['Ethnicity'].value_counts(dropna=False)
print(ethnic_counts)

Ethnicity
WHITE                                                                                                                       395
White                                                                                                                       332
ASIAN                                                                                                                       175
Asian                                                                                                                       153
Race/Ethnicity Unknown                                                                                                      104
BLACK, AFR AMER                                                                                                              90
Black or African American                                                                                                    69
Hispanics of any race                                                                         

In [109]:
urm_counts=combinedDF['URM'].value_counts(dropna=False)
print(urm_counts)

URM
1    941
0    727
Name: count, dtype: int64


In [113]:
combinedDF['IntlStudent'] = np.where(
    combinedDF['Ethnicity'].str.contains('Alien', case=False, na=False),
    1,
    0)
gui = show(combinedDF)

PandasGUI INFO — pandasgui.gui — Opening PandasGUI
C:\Users\iabak\AppData\Local\Temp\ipykernel_5368\1222976117.py:5: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

C:\Users\iabak\AppData\Local\Temp\ipykernel_5368\1222976117.py:5: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

C:\Users\iabak\AppData\Local\Temp\ipykernel_5368\1222976117.py:5: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

C:\Users\iabak\AppData\Local\Temp\ipykernel_5368\

In [115]:
from scipy.stats import chi2_contingency
filtered_df3 = combinedDF[combinedDF['Gender'].isin(['F', 'M'])]
contingency_table = pd.crosstab(filtered_df3['Gender'], filtered_df3['DecisionRecode'])
chi2_stat, p_value, dof, expected = chi2_contingency(contingency_table)
N=filtered_df3.shape[0]
print(f"Number of observations (N): {N}")
print(f"Chi-square statistic: {chi2_stat}")
print(f"P-value: {p_value}")
print(f"Degrees of freedom: {dof}")
print(f"Expected frequencies table:\n{expected}")

Number of observations (N): 1629
Chi-square statistic: 0.0035937803230960902
P-value: 0.9521969330977005
Degrees of freedom: 1
Expected frequencies table:
[[952.81031308  79.18968692]
 [551.18968692  45.81031308]]


In [117]:
filtered_df4 = combinedDF[~combinedDF['Ethnicity'].str.contains('Unknown', 'UNKNOWN')]
contingency_table = pd.crosstab(filtered_df4['URM'], filtered_df4['DecisionRecode'])
chi2_stat, p_value, dof, expected = chi2_contingency(contingency_table)
N=filtered_df4.shape[0]
print(f"Number of observations (N): {N}")
print(f"Chi-square statistic: {chi2_stat}")
print(f"P-value: {p_value}")
print(f"Degrees of freedom: {dof}")
print(f"Expected frequencies table:\n{expected}")

Number of observations (N): 1564
Chi-square statistic: 0.13664395311512664
P-value: 0.7116404379419481
Degrees of freedom: 1
Expected frequencies table:
[[667.50127877  59.49872123]
 [768.49872123  68.50127877]]


In [121]:
filtered_df5 = combinedDF
contingency_table=pd.crosstab(combinedDF['IntlStudent'], combinedDF['DecisionRecode'])
chi2_stat, p_value, dof, expected=chi2_contingency(contingency_table)
N=filtered_df5.shape[0]
print(f"Number of observations (N): {N}")
print(f"Chi-square statistic: {chi2_stat}")
print(f"P-value: {p_value}")
print(f"Degrees of freedom: {dof}")
print(f"Expected frequencies table:\n{expected}")

Number of observations (N): 1668
Chi-square statistic: 0.07856391512270047
P-value: 0.7792530639389101
Degrees of freedom: 1
Expected frequencies table:
[[1463.15107914  128.84892086]
 [  69.84892086    6.15107914]]
